ci: :green_heart: Repair publish workflow cache nextjs

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -84,10 +84,29 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v3
 
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::pnpm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::pnpx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: 18.x
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
 
       - uses: pnpm/action-setup@v2
         name: Install pnpm
@@ -95,11 +114,21 @@ jobs:
           version: 7.x
           run_install: false
 
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
       - name: Install dependencies
-        run: pnpm install --no-frozen-lockfile --no-optional
-
-      - name: Build App
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
         run: pnpm run build
+
       - run: pnpm install
       - run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
       - run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
